### ISSUE TITLE
Part 3 of the mod list vs BWFixpack

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET-Compatibility-List#23]
Consider to remove this part of the list.
BWFixpack is no longer updated and it must be installed as a whole with no option to patch only selected mods. If a user runs the patch for an EET preparation, the fixpack will also patch or attempt to patch mods that are long updated. The EET should not recommend such a procedure. There are side effects even if the mod itself is not even part of fixpack but affected by the (outdated) area and item fixers that are part of the process.
Just food for thought.

**Comment by K4thos** [comment]
Branwen, Kelsey, Keto and Reunion will likely receive native EET support soon (courtesy of Jestey that handles recent mod updates). As for Wild Mage Additions and Wizard Slayer Rebalancing I've tried to contact their authors recently but not replies as of yet. When it comes to Divine Remix I'm not sure why the mod is even in third section when the beta hosted on github clearly has native EET code.

So yeah, once there are just 2 mods left removing whole section completely sounds ok.

**Comment by RoxanneSHS** [comment]
My main concern is that recommending the use of BWFixpack has a negative impact on mods that are not in part 3 of the list anymore. Fixpack applies patches to all mods it finds and that do not raise errors due to clear version mismatch. There are quite a few that get patched with no longer appropriate fixes just because a user want one mod from part 3. The result can be bugged EET installations.

Yes, you can argue that the user is responsible for applying fixpack. Still, recommending it in your instructions makes it sound to a non-expert like being the right thing to do.

**Comment by ALIENQuake** [comment]
I've made update to WSR, waiting for wisp to release it.

**Comment by ALIENQuake** [comment]
WSR was updated, two more to go

**Comment by K4thos** [comment]
done, thank
